name: be_healthy
description: A new Flutter application that provides tracking the reception

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.17

  cupertino_icons: ^0.1.3

  flutter_local_notifications: ^0.8.4+3

  sqflite: ^1.1.7+3

  rxdart: ^0.22.6

  path: ^1.6.4

  provider: ^3.2.0

  date_range_picker: ^1.0.6

  percent_indicator: ^2.1.1+1

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-Regular.ttf